version: '3.3'
services:
  fc_main:
    container_name: 'fc-main'
    ports:
      - '3000:3000'
      - '8000:8000'
    tty: true
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: .
      args:
          - NODE_ENV=development
    volumes: 
      - './:/src'
      #NOTE: uncomment the line below to link your local plugins folder to the container to develop in the container.
      #- '../common-hapi-plugins:/node_modules/@freecycle/common-hapi-plugins'
    hostname: 'dev.freecycle.org'
    depends_on:
      - 'redis'
    extra_hosts:
      - 'dev.freecycle.org:127.0.0.1'
    environment:
      - NODE_ENV=development
    command: npm run dev:watch
  redis:
    container_name: 'fc-redis'
    ports:
      - '6379:6379'
    image: redis